app:
  message: This is the Production env property file
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prodDB
    user-name: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    