app:
  message: This is the Dev environment's properties file
spring:  h2:    console:      enabled: true
      path: /h2
  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password: sa